---
- name: Config nginx proxy for app 
  vars_files:
    - pars/in_ng_proxy_par.yml
  vars:
  hosts: "{{ host }}" 
  tasks:
    - name: gen prot list script
      template: src="pars/chk_port.sh.j2" dest="/tmp/chk_port.sh" owner=root group=root mode=0700
     
    - name: gen port usage list
      shell: /tmp/chk_port.sh list; cat /tmp/port_grep.log
      register: result_list
    
    - name: port verify 
      debug: msg='the used port including {{ result_list.stdout }} you are trying to use {{ proxy_port }}'

    - name: conflict port check
      shell: /tmp/chk_port.sh conflict_chk
      register: result_conf_chk
 
#    - name: chk
#      debug: var=result_conf_chk

    - name: generate nginx proxy file 
      template: src="pars/nginx.conf.j2" dest="/usr/local/nginx/conf/vhosts/{{ conf_env }}.{{ service_name }}{{ sequence }}.conf" owner=root group=root mode=0600
      notify: restart nginx
      when: result_conf_chk.stdout == "0"

    - name: enable firewall port "{{ proxy_port }}"
      firewalld: zone=public port={{ proxy_port }}/tcp permanent=true state=enabled
      notify: reload firewall
      when: result_conf_chk.stdout == "0" 

  handlers:
    - name: restart nginx
      shell: /usr/local/nginx/sbin/nginx -s reload

    - name: reload firewall
      shell: /usr/bin/firewall-cmd --reload
